spring:
  datasource:
    url: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=1000
    driverClassName: org.h2.Driver
    username: sa
    password:
#    data: classpath:db/table.sql
#    schema: classpath:db/schema.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
#logging:
#  level: debug

#jpa
#  spring.jpa.hibernate.ddl-auto=validate
#  spring.jpa.show-sql=true
#  spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#  logging.level.org.hibernate.SQL=debug
