server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
#Spring boot视图配置
spring:
  messages:
    encoding: UTF-8
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
filesize-max: 5242880
storage-folder: app_data